name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: ap-southeast-1
      - run: go install github.com/kaihendry/toc/cmd/toc@latest
      - run: sudo apt install -y m4
      - uses: kaihendry/actions/goredo@main
      - run: redo upload
